/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";

export default function Avatar({ animation, ...props }) {
  const { headFollow, cursorFollow, wireframe } = useControls({
    headFollow: false,
    cursorFollow: false,
    wireframe: false,
  });

  const group = useRef();
  const { nodes, materials } = useGLTF("models/646d9dcdc8a5f5bddbfac913.glb");

  // Safely load animations
  const { animations: typingAnimation = [] } = useFBX("animations/Typing.fbx");
  const { animations: standingAnimation = [] } = useFBX("animations/Standing Idle.fbx");
  const { animations: fallingAnimation = [] } = useFBX("animations/Falling Idle.fbx");

  if (typingAnimation[0]) typingAnimation[0].name = "Typing";
  if (standingAnimation[0]) standingAnimation[0].name = "Standing";
  if (fallingAnimation[0]) fallingAnimation[0].name = "Falling";

  const allAnimations = [typingAnimation[0], standingAnimation[0], fallingAnimation[0]].filter(Boolean);
  const { actions } = useAnimations(allAnimations, group);

 useEffect(() => {
  if (!actions) return;
  const selectedAction = actions[animation];
  if (selectedAction) {
    selectedAction.reset().fadeIn(0.5).play();
    return () => {
      selectedAction.fadeOut(0.5);
    };
  } else {
    console.warn(`Animation "${animation}" not found`, Object.keys(actions));
  }
}, [animation, actions]);


  // Follow logic
  useFrame((state) => {
    if (headFollow && group.current?.getObjectByName("Head")) {
      group.current.getObjectByName("Head").lookAt(state.camera.position);
    }

    if (cursorFollow && group.current?.getObjectByName("Spine2")) {
      const target = new THREE.Vector3(state.mouse.x * 10, state.mouse.y * 10, 1);
      group.current.getObjectByName("Spine2").lookAt(target);
    }
  });

  // Wireframe toggle
  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe]);

  return (
    <group {...props} ref={group} dispose={null}>
      <group>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/646d9dcdc8a5f5bddbfac913.glb");
